register_device:
  name: Register as a general-use smartphone
  description: >-
    After the registered management smartphone starts registration mode, register
    this Home Assistant Bluetooth connection as a general-use smartphone.
  target:
    entity:
      integration: ykkap_smart_lock
      domain: lock
  fields:
    request_adv_key:
      name: Get state-synchronization information
      description: Get and save the information needed to retrieve and synchronize the lock's locked or unlocked state.
      required: false
      default: true
      selector:
        boolean:
    exit_registration:
      name: Exit registration mode
      description: Exit the lock's registration mode after registration is complete.
      required: false
      default: true
      selector:
        boolean:
